name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install
        run: pnpm install --frozen-lockfile
        working-directory: ./7integra
      - name: Lint
        run: pnpm lint
        working-directory: ./7integra
      - name: Test
        run: pnpm test -- --run
        working-directory: ./7integra
      - name: Build
        run: pnpm build
        working-directory: ./7integra
